export const MUTATION_TYPE = {
  SET_HEADER_DATA: 'SET_HEADER_DATA',
  SET_FOOTER_DATA: 'SET_FOOTER_DATA',
  SET_NAVIGATION_DATA: 'SET_NAVIGATION_DATA',
  SET_SOCIAL_DATA: 'SET_SOCIAL_DATA',

  SET_STRINGS: 'SET_STRINGS',
  SET_LANGS: 'SET_LANGS'
}

export const BASE_URL = process.env.PRISMIC_ENDPOINT
